Facebook login
mato2593/Target-MVD-Mathias pull request #3
Opened 2017-08-18 20:09 UTC by mato2593

This PR includes facebook login, some fixes in the user object parsing after changing the server url and the inclusion of the X-USER-TOKEN header to the requests if the user is logged in.

https://trello.com/c/xLLgqbjA/1-3-as-a-user-i-should-be-able-to-use-my-facebook-account-to-sign-in-up

![facebook-sign-in](https://user-images.githubusercontent.com/5600321/29474462-3635bf62-8432-11e7-92f2-54dd64c487d2.gif)

2017-08-18 20:25 UTC, ericnpc commented on Target-MVD-Mathias/ViewControllers/SignInViewController.swift
> +      }
In all of this `if, else if, else` block it seems like you use that result a lot, so I would put it inside a `if let result = result {.. your code here..}` so the code looks cleaner

2017-08-18 20:27 UTC, ericnpc-zz requested changes
Small issue

2017-08-18 20:38 UTC, mato2593 commented on Target-MVD-Mathias/ViewControllers/SignInViewController.swift
> +      }
Done

2017-08-18 20:47 UTC, ericnpc-zz approved these changes

2017-08-18 21:08 UTC, pMalvasio commented on Target-MVD-Mathias/ViewControllers/SignInViewController.swift
> +      UIApplication.shared.keyWindow?.rootViewController = UIStoryboard.instantiateViewController(HomeViewController.self, storyboardIdentifier: "Main")
The default value for the parameter `storyboardIdentifier ` is "Main" so you can delete this from the method

2017-08-18 21:08 UTC, pMalvasio commented on Target-MVD-Mathias/ViewControllers/SignUpViewController.swift
> +      UIApplication.shared.keyWindow?.rootViewController = UIStoryboard.instantiateViewController(HomeViewController.self, storyboardIdentifier: "Main")
Same here

2017-08-18 21:08 UTC, pMalvasio commented on Target-MVD-Mathias/ViewControllers/SignInViewController.swift
> +                                UIApplication.shared.keyWindow?.rootViewController = UIStoryboard.instantiateViewController(HomeViewController.self, storyboardIdentifier: "Main")
And here

2017-08-18 21:21 UTC, pMalvasio commented on Target-MVD-Mathias/AppDelegate.swift
> +      let vc = UIStoryboard.instantiateViewController(HomeViewController.self, storyboardIdentifier: "Main")
And here

2017-08-18 21:22 UTC, pMalvasio requested changes
Some comments

2017-08-21 14:00 UTC, glm4 commented on Target-MVD-Mathias/Manager/UserDataManager.swift
> +    if let token = defaults.object(forKey: "access-token") as? String {
this is the same as ` return defaults.object(forKey: "access-token") as? String`. If it can't be parsed nil will be returned.

2017-08-21 14:26 UTC, fernandatoledo approved these changes

2017-08-21 14:52 UTC, pMalvasio approved these changes

2017-08-21 15:01 UTC, CamilaMoscatelli approved these changes

2017-08-21 15:11 UTC, mjurfest approved these changes

2017-08-21 15:53 UTC, glm4 approved these changes

2017-08-21 15:53 UTC, merged